#!/bin/sh

export USER=user
export HOME=/home/user

groups="$(id -Gn "$USER" | tr ' ' ':')"
svdir="$HOME/.local/service"

. /usr/local/share/lxcex-xdg.sh

exec chpst -u "$USER:$groups" runsvdir "$svdir"
