#!/bin/sh -e

upgrade()
{
    container=$1
    echo "--------------------"
    echo "Upgrading $container"
    echo "--------------------"
    subid=`stat -c %u /var/lib/lxc/$container/rootfs`
    if [ $subid = 0 ] ; then
        chroot /var/lib/lxc/$container/rootfs apt update
        chroot /var/lib/lxc/$container/rootfs apt -y dist-upgrade
        chroot /var/lib/lxc/$container/rootfs apt clean
    else
        lxc-usernsexec -m b:0:$subid:65536 -- chroot /var/lib/lxc/$container/rootfs apt update
        lxc-usernsexec -m b:0:$subid:65536 -- chroot /var/lib/lxc/$container/rootfs apt -y dist-upgrade
        lxc-usernsexec -m b:0:$subid:65536 -- chroot /var/lib/lxc/$container/rootfs apt clean
    fi
}

if [ $# = 0 ] ; then
    echo "---------------------"
    echo "Upgrading base system"
    echo "---------------------"
    apt update
    apt -y dist-upgrade
    apt clean

    for container in `lxc-ls -1` ; do
        upgrade $container
    done
else
    for container in $@ ; do
        upgrade $container
    done
fi

