#!/bin/sh -e

upgrade()
{
    container=$1
    echo "--------------------"
    echo "Upgrading $container"
    echo "--------------------"
    lxc-chroot $container apt update
    lxc-chroot $container apt -y dist-upgrade
    lxc-chroot $container apt -y autoremove
    lxc-chroot $container apt clean
}

if [ $# = 0 ] ; then
    echo "---------------------"
    echo "Upgrading base system"
    echo "---------------------"
    apt update
    apt -y dist-upgrade
    apt clean

    for container in `lxc-ls -1` ; do
        upgrade $container
    done
else
    for container in $@ ; do
        upgrade $container
    done
fi

